services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    command: [nginx-debug, '-g', 'daemon off;'] # debug mode

  dashboard-app:
    image: node:latest
    container_name: dashboard-app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sleep infinity

  to-do-app:
    image: node:latest
    container_name: to-do-app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: sleep infinity

