services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    command: [nginx-debug, '-g', 'daemon off;'] # debug mode

  dashboard-app:
    image: node:latest
    container_name: dashboard-app
    volumes:
      - .:/app
    command: sleep infinity

  to-do-app:
    image: node:latest
    container_name: to-do-app
    volumes:
      - .:/app
    command: sleep infinity

  database:
    image: mongo
    container_name: database
    # restart: always
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    image: node:latest
    container_name: backend
    volumes:
      - ./backend:/app
    command: sleep infinity
    

